### ISSUE TITLE
Two libraries open - close leads to crash

### ISSUE THREAD

**Issue by koppor** [LoayGhreeb/jabref#10]
- a.bib
- b.bib
- search in b.bib
- focus a.bib
- close a.bib
- b.bib is shown and following exception

![image](https://github.com/user-attachments/assets/1a9919cf-1416-4665-bb5f-4ec006a74422)

**Comment by LoayGhreeb** [comment]
It was an issue with the search groups and fixed in [`JabRef@e4c9d91`](https://github.com/JabRef/jabref/commit/e4c9d915bd6221e09345920b2087a0d90f5c9dad#diff-7df7817bb35bc6a16bdae13f19626c97697955a613b12f7de6828ef639eeb6b1).
