### ISSUE TITLE
Code quality: Refactor `updateSearchMatches` to `clearSearchMatches` and `setSearchMatches`

### ISSUE THREAD

**Issue by koppor** [LoayGhreeb/jabref#12]
Minor thing.

Source: https://github.com/JabRef/jabref/pull/11542/files/a1461e59c34e4c9664ec6c6644e2ec7d5a00bc7e..bb900474749da16f15fa599ebc3516415af7dc38#r1735350307

**Comment by LoayGhreeb** [comment]
Fixed in https://github.com/JabRef/jabref/commit/5bcb82d5f0fbff403bf253fad0527b508bd743f5.
