### ISSUE TITLE
Check org.apache.lucene:lucene-sandbox

### ISSUE THREAD

**Issue by koppor** [LoayGhreeb/jabref#7]
Is this really necessary? :)

**Comment by LoayGhreeb** [comment]
> Is this really necessary? :)

It isn't used anywhere, so we can remove it from `external-libraries.md`

**Comment by koppor** [comment]
> > Is this really necessary? :)
> 
> It isn't used anywhere, so we can remove it from `external-libraries.md`

Please check the dependency tree. You can get it via the gradle task `dependencyReport`. There must be some transitive dependency on that. Otherwise, it does not end up in `external-libraries.md`

See https://github.com/JabRef/jabref/blob/7b4c3df68d14c25f3ee9a19acb7e5139789113d7/external-libraries.md?plain=1#L684 for the process.

**Comment by LoayGhreeb** [comment]
> Please check the dependency tree. You can get it via the gradle task `dependencyReport`. There must be some transitive dependency on that. Otherwise, it does not end up in `external-libraries.md`
> 
> See [JabRef/jabref@`7b4c3df`/external-libraries.md?plain=1#L684](https://github.com/JabRef/jabref/blob/7b4c3df68d14c25f3ee9a19acb7e5139789113d7/external-libraries.md?plain=1#L684) for the process.

Looks like it’s used internally:

```
+--- org.apache.lucene:lucene-queryparser:9.11.1
|    +--- org.apache.lucene:lucene-core:9.11.1
|    +--- org.apache.lucene:lucene-queries:9.11.1
|    |    \--- org.apache.lucene:lucene-core:9.11.1
|    \--- org.apache.lucene:lucene-sandbox:9.11.1
|         +--- org.apache.lucene:lucene-core:9.11.1
|         \--- org.apache.lucene:lucene-queries:9.11.1 (*)
```

**Comment by koppor** [comment]
Can it be excluded when loading? Does it still work then?

**Comment by LoayGhreeb** [comment]
> Can it be excluded when loading? Does it still work then?

I tried:
```
(implementation "org.apache.lucene:lucene-queryparser:$luceneVersion") {
    exclude group: 'org.apache.lucene', module: 'lucene-sandbox'
}
```

But it didn't work:
```
Task :run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Module org.apache.lucene.sandbox not found, required by org.apache.lucene.queryparser
```
