### ISSUE TITLE
Bring back stripes

### ISSUE THREAD

**Issue by koppor** [LoayGhreeb/jabref#8]
Old JabRef:

![image](https://github.com/user-attachments/assets/10cc462d-c169-42af-b8b3-3dde2ef1d1a2)

New JabRef (introduced by https://github.com/JabRef/jabref/pull/11510)

![image](https://github.com/user-attachments/assets/a393e09b-7773-4344-a34b-bcacb45080f2)

See that other apps also have these stripes: https://www.papersapp.com/

If they have too high contrast, try to play around with only a slight luminance difference.

Not everything got worse with JabRef 4.0 😅.

Screenshot JabRef 3.8.1: https://www.filehorse.com/download-jabref/28848/

(The spacing bertween the lines can also be reduced.)

**Comment by subhramit** [comment]
+1 on this. The stripes looked better.

**Comment by LoayGhreeb** [comment]
https://github.com/JabRef/jabref/pull/11510#issuecomment-2241759920.
> It might be worthwhile enhancing the colours of state 2 (contains search term but does not belong to group) and state 3 (does not contain search term but belongs to group), i. e. making them darker. At the moment, especially the greyish colour of state 2 is very similar to the grey in state 1 (state 1, which are items that contain both the search term and belong to the selected group, will display lines alternating white and grey colours when multiple elements are present).

If I revert the changes and apply stripes only to the first state, there will be three colors but only two states (matched to groups and not matched to groups):
- Matched to groups will have two colors.
- Not matched to groups will have one color.

![image](https://github.com/user-attachments/assets/f7ca6fd7-f485-4f97-a735-96688a444c43)

Applying stripes to all states would be very distracting as each of the four states would have two colors:
![image](https://github.com/user-attachments/assets/f445d138-5052-4bd4-8d39-25543be20c0a)

**Comment by LoayGhreeb** [comment]
Can you check if this is better? 
![image](https://github.com/user-attachments/assets/4dd0b8ab-b620-4deb-a1aa-992e77b9306f)
